# Generated by Django 5.1.3 on 2024-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('resume_data', models.TextField()),
                ('clean_data', models.TextField()),
                ('entities', models.JSONField()),
                ('extracted_keywords', models.JSONField()),
                ('keyterms', models.JSONField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('emails', models.JSONField()),
                ('phones', models.JSONField()),
                ('years', models.JSONField()),
                ('bi_grams', models.TextField(blank=True, null=True)),
                ('tri_grams', models.TextField(blank=True, null=True)),
                ('pos_frequencies', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
